### ISSUE TITLE
Backend - Structure model for User

### ISSUE THREAD

**Issue by juanfer2** [juanfer2/trullo_backend#1]
Defined what field must be have this table

Check this history:
https://devchallenges.io/challenges/N1fvBjQfhlkctmwj1tnw

**Comment by hbuitgu** [comment]
![image](https://user-images.githubusercontent.com/89142754/148664834-3c32ba7c-fa86-4465-b07c-b9287d396b81.png)

**Comment by juanfer2** [comment]
@hbuitgu and me desing this structure for table in database
![image](https://user-images.githubusercontent.com/64051193/149603222-37ea258f-1cee-4731-8dbf-6bb36bcbc9b1.png)
